services:
  postgres:
    image: postgres:13.4
    container_name: marche-public-database
    env_file: .env
    environment:
      PGUSER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  appels_offres:
    build:
      context: .
      dockerfile: Dockerfile
    image: appels_offres
    container_name: appels_offres
    command: bash entrypoint.sh
    volumes:
      - .:/ao_website
    env_file: .env
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  db:
    driver: local
